/**
 * Every word the player reads, in one place.
 *
 * The product is in English (`docs/SPEC.md` section 1). Keeping the text here
 * rather than inside components means it can be translated later without
 * touching a single component, and it means nobody has to hunt through the
 * interface to fix a typo.
 */
export const strings = {
  appName: 'Atheriam',
  landing: {
    skip: 'Skip to discover',
    navigation: 'Main navigation',
    discover: 'The city',
    create: 'Make it yours',
    questions: 'Good to know',
    login: 'Log in',
    eyebrow: 'YOUR EVERYDAY, A LITTLE MORE PLAYFUL',
    title: 'A little city.',
    titleAccent: 'A world of possibilities.',
    description:
      'Meet your people. Make a space that feels like you. Open the doors to your next big idea — all in one shared pixel world.',
    join: 'Find your place',
    takeLook: 'Take a look around',
    requirements: 'Play in your browser · Free to join · Ages 18+',
    heroAlt:
      'An original pixel illustration of neighbours chatting around a fountain, contemporary shops and a lakeside café.',
    cityName: 'Atheriam Central',
    cityCaption: 'A new neighbourhood. Your next chapter.',
    cityFacts: 'Our first city',
    facts: [
      'One shared city',
      '10 commercial addresses',
      '5 public buildings',
      'Endless little connections',
    ],
    discoverEyebrow: 'A PLACE TO BELONG',
    discoverTitle: 'Small moments.\nReal connections.',
    discoverCopy:
      'A familiar face in the square. An idea shared over coffee. A space you cannot wait to show your friends.',
    features: [
      {
        title: 'Meet in the middle.',
        copy: 'Drop into Central Square, catch up at the lounge, or take the long way home through the lakeside park.',
        note: 'YOUR PEOPLE ARE OUT THERE',
      },
      {
        title: 'Make room for you.',
        copy: 'Choose your look, arrange your furniture and give your own environment its personality. Invite friends to see what you have made.',
        note: 'A LITTLE MORE YOU',
      },
      {
        title: 'Open something good.',
        copy: 'Buy a commercial address with Crowns, name your business and welcome the neighbourhood. Trade game items with other residents.',
        note: 'FROM IDEA TO OPEN DOORS',
      },
    ],
    shopAlt:
      'Contemporary creative studios and a café with colourful storefronts in the illustrated city.',
    shopCaption: 'A corner of the city. A whole lot of you.',
    createEyebrow: 'BUILT AROUND YOUR IDEAS',
    createTitle: 'Your name\non the door.',
    createCopy:
      'An art studio. A neighbourhood shop. A place to bring your friends together. Give your ideas an address in Atheriam Central.',
    steps: [
      {
        title: 'Find your corner',
        copy: 'Explore the city guide and review the available commercial properties and their Crown prices.',
      },
      {
        title: 'Make it your own',
        copy: 'Name your business, style the interior and choose who can come inside.',
      },
      {
        title: 'Welcome the neighbourhood',
        copy: 'Publish your space, invite people over and offer your game items for sale.',
      },
    ],
    startCreating: 'Start your story',
    questionsEyebrow: 'BEFORE YOU MOVE IN',
    questionsTitle: 'Good to know.',
    faq: [
      {
        q: 'What is Atheriam?',
        a: 'Atheriam is a multiplayer social city for adults. Walk around, chat, decorate your own spaces and take part in a player-run economy.',
      },
      {
        q: 'Do I need to download anything?',
        a: 'No download is needed. Create an account and play in your browser. On a phone, landscape gives you more room to explore.',
      },
      {
        q: 'How do businesses work?',
        a: 'The first city has ten commercial properties and five public buildings. Available properties can be bought with the in-game currency, Crowns. Owners can name, decorate and publish their businesses.',
      },
      {
        q: 'Are Crowns real money?',
        a: 'Crowns are game currency. They are used for properties and item trades inside Atheriam, with no cash-out or promised financial return.',
      },
      {
        q: 'Can I meet privately with friends?',
        a: 'The lounge has private meeting rooms that you can reserve and invite other residents into. The public square and lounge are there for spontaneous catch-ups.',
      },
      {
        q: 'Who can join?',
        a: 'Atheriam is for people aged 18 and over. Residents can block and report players, and moderators can act on reports.',
      },
    ],
    inviteEyebrow: 'THE CITY IS BETTER WITH COMPANY',
    inviteTitle: 'See you in the square.',
    inviteCopy:
      'Your next friend, favourite corner or big little idea could be just around the block.',
    footer: 'An original social world. Made for people, places and possibilities.',
  },
  city: {
    open: 'City guide',
    title: 'Atheriam Central',
    subtitle: 'Find your place in the neighbourhood.',
    all: 'All addresses',
    sale: 'For sale',
    yours: 'My businesses',
    public: 'Public spaces',
    municipal: 'City-owned',
    owned: 'Player-owned',
    yourProperty: 'Your business',
    loading: 'Finding the city addresses…',
    retry: 'Try again',
    close: 'Back to the city',
    buy: 'Review purchase',
    confirm: 'Buy this property',
    cancel: 'Cancel',
    locate: 'Walk to entrance',
    enter: 'Enter environment',
    entering: 'Opening the door…',
    entryFailed: 'The door did not open. Please try again.',
    environment: 'Environment',
    accessInGuide: 'Change access, floor and wall finishes in City guide → My businesses.',
    purchaseTitle: 'A place for your next idea.',
    price: 'Purchase price',
    balance: 'Your balance',
    purchaseHelp: 'Pay with your in-game Crowns. This address becomes yours to name and decorate.',
    purchased: 'The keys are yours. Give your business a name.',
    settings: 'Business settings',
    name: 'Business name',
    description: 'About your business',
    access: 'Who can enter',
    publish: 'Show my business in the directory',
    floor: 'Floor finish',
    wall: 'Wall colour',
    save: 'Save business',
    saved: 'Your business settings are saved.',
    empty: 'No addresses in this view yet.',
    oak: 'Warm oak',
    stone: 'Pale stone',
    tile: 'Studio tile',
    cream: 'Cream',
    teal: 'Teal',
    rose: 'Rose',
  },
  tagline: 'A little world. A place of your own.',
  welcome: {
    eyebrow: 'YOUR CITY. YOUR COMMUNITY.',
    title: 'Meet your people.\nMake your place.',
    description:
      'Meet in the square, create your own spaces and bring your next business idea to life.',
    explore: 'Explore the city',
    talk: 'Meet your neighbours',
    decorate: 'Make yourself at home',
    footer: 'Made for slow afternoons & new friendships.',
    version: 'V1.0 · A new chapter',
    loginTitle: 'Welcome home.',
    createTitle: 'Your story starts here.',
    loginCopy: 'The square is waiting. Come on in.',
    createCopy: 'A new face. A new home. A whole town to meet.',
    world: 'Central Square',
    market: 'Market Quarter',
    park: 'Lakeside Park',
    neighbourhood: 'Business District',
    town: 'Atheriam town',
    online: 'Live world',
    lookNames: [
      'River blue',
      'Autumn coral',
      'Market gold',
      'Forest green',
      'Heather violet',
      'Evening blue',
    ],
    look: 'Your look',
    chooseLook: 'Choose your look',
    saveLook: 'Wear this look',
    lookHelp: 'A little more you. Your neighbours will see your new look.',
    lookSaved: 'Your new look is saved.',
    credits: 'Art & credits',
    controls: 'Walk',
    north: 'Walk north',
    south: 'Walk south',
    west: 'Walk west',
    east: 'Walk east',
    portraitHint: 'Tap a path to explore. Open chat to say hello.',
  },

  auth: {
    createTab: 'Create an account',
    loginTab: 'Log in',

    nameLabel: 'Your name in the city',
    namePlaceholder: 'Aldric',
    nameHelp: 'Three to twenty letters or numbers. Spaces are fine.',

    emailLabel: 'Email address',
    emailPlaceholder: 'you@example.com',

    passwordLabel: 'Password',
    passwordHelp: 'At least ten characters. Longer is better than complicated.',

    birthdayLabel: 'Date of birth',
    birthdayHelp: 'We ask because Atheriam is for adults only.',

    adultLabel: 'I confirm that I am 18 or over.',

    createSubmit: 'Create my account',
    loginSubmit: 'Enter the city',
    working: 'One moment…',

    ageNotice: 'Atheriam is for adults. You must be 18 or over to play.',

    forgotLink: 'I have forgotten my password',
    forgotTitle: 'Choosing a new password',
    forgotCopy:
      'Tell us the email address you signed up with and we will send you a link. The link works once, and only for an hour.',
    forgotSubmit: 'Send me a link',
    forgotSent:
      'If that address has an account, a link is on its way. Have a look in your spam folder if it does not arrive.',
    backToLogin: 'Back to logging in',

    resetTitle: 'Choose a new password',
    resetCopy: 'Type it twice, so a typo cannot lock you out.',
    newPasswordLabel: 'New password',
    repeatPasswordLabel: 'Type it again',
    resetSubmit: 'Save my new password',
    resetDone: 'Your password is changed. You can log in with it now.',
    logOut: 'Log out',
  },

  errors: {
    nameTooShort: 'That name is too short — three letters at least.',
    nameTooLong: 'That name is too long — twenty letters at most.',
    nameBadCharacters: 'Please use only letters, numbers, spaces, - and _.',
    passwordTooShort: 'Your password must be at least ten characters.',
    notAnEmail: 'That does not look like an email address.',
    noBirthday: 'Please tell us your date of birth.',
    notConfirmedAdult: 'Please confirm that you are 18 or over.',
    passwordsDiffer: 'Those two do not match. Please type the same password twice.',
    'bad-ticket': 'Your pass to the city expired. Please try again.',
    'already-online': 'That character is already in the city.',
    'server-full': 'The city is full right now. Please try again in a moment.',
    kicked: 'A moderator removed you from the city.',
    banned: 'This account is banned from Atheriam.',
    shutdown: 'The city is restarting. Come back shortly.',
    'protocol-error': 'The connection sent something unexpected and was closed.',
    idle: 'You were away for a long time, so you left the city.',
    'could not reach the world': 'Could not reach the city. Is the world server running?',
    'connection lost': 'The connection dropped.',
    'you left': 'You left the city.',
    unknown: 'Something went wrong. Please try again.',
  } as Record<string, string>,

  hud: {
    loadingArt: 'Opening the town gates…',
    artError: 'The artwork could not load. Please refresh to try again.',
    connecting: 'Connecting…',
    joining: 'Entering the city…',
    playersNearby: (count: number): string =>
      count === 1 ? '1 person nearby' : `${count} people nearby`,
    position: (x: number, y: number): string => `${x}, ${y}`,
  },

  hints: {
    desktop: 'Click a tile to walk there, WASD to step, Enter to talk.',
    touch: 'Tap a tile to walk there. Use the box below to talk.',
  },

  chat: {
    logLabel: 'What people near you are saying',
    inputLabel: 'Say something',
    placeholder: 'Say something to the people near you…',
    send: 'Say',
    empty: 'Nobody nearby has said anything yet.',
    nameTitle: (name: string): string => `What to do about ${name}`,
    muted: 'A moderator has stopped you talking for now.',
    hide: 'Hide chat',
    show: (unread: number, more: boolean): string =>
      unread === 0 ? 'Show chat' : `Show chat (${unread}${more ? '+' : ''})`,
    tooChatty: 'That was a lot at once. Give it a moment.',
  },

  pouch: {
    title: 'Your purse',
    open: 'Purse',
    loading: '…',
    claimDaily: "Collect today's reward",
    claimed: (amount: string): string => `You collected ${amount}.`,
    alreadyClaimed: 'You have already collected today. Come back tomorrow.',
    carrying: (count: number): string =>
      count === 1 ? 'You are carrying 1 thing' : `You are carrying ${count} things`,
    empty: 'Your hands are empty.',
    recently: 'Recently',
    close: 'Close',
  },

  house: {
    title: 'Your house',
    visiting: 'Somebody else’s house',
    open: 'House',
    goHome: 'Go home',
    visit: 'Call on them at home',
    leave: 'Step outside',
    door: 'Who may come in',
    access: {
      nobody: 'Nobody',
      welcomed: 'People I welcome',
      everyone: 'Anybody',
    } as Record<string, string>,
    accessHelp: {
      nobody: 'Only you can come in.',
      welcomed: 'Only the people on your list can come in.',
      everyone: 'Anybody in the city can walk in.',
    } as Record<string, string>,
    welcomed: 'People you have welcomed',
    nobodyWelcomed: 'Nobody yet.',
    stopWelcoming: 'stop welcoming',
    welcomeLabel: 'Name of somebody to welcome',
    welcomePlaceholder: 'Their name in the city',
    welcomeSubmit: 'Welcome',
    arranging: 'Arranging',
    pickSomething: 'Choose something below, then tap where it should stand.',
    nowTap: (name: string): string => `Now tap where the ${name.toLowerCase()} should stand.`,
    choose: 'choose',
    chosen: 'chosen — tap the floor',
    noFurniture: 'You are not carrying any furniture.',
    standingHere: 'Standing here',
    bare: 'Nothing yet. It is a bare room.',
    at: (x: number, y: number): string => `${x}, ${y}`,
    turn: 'turn',
    pickUp: 'pick up',
    placed: 'Put down.',
    notWelcome: 'The door is shut.',
  },

  trade: {
    title: (name: string): string => `Trading with ${name}`,
    explain:
      'Everything you put on the table leaves your hands straight away. Nothing is swapped until you both agree, and changing anything means agreeing again.',
    yours: 'What you are giving',
    theirs: (name: string): string => `What ${name} is giving`,
    nothingYet: 'Nothing yet.',
    putOn: 'Your things',
    put: 'put on the table',
    takeBack: 'take back',
    moneyLabel: 'Crowns to put on the table',
    moneyPlaceholder: '0.00',
    setMoney: 'Set',
    purse: (amount: string): string => `You have ${amount} left in your purse.`,
    agree: 'I agree to this',
    waiting: 'Waiting for them…',
    youAgreed: 'You have agreed.',
    youHaveNot: 'You have not agreed yet.',
    theyAgreed: (name: string): string => `${name} has agreed.`,
    theyHaveNot: (name: string): string => `${name} has not agreed yet.`,
    callOff: 'Call it off',
    done: 'The trade is done.',
    ended: 'The trade ended.',
    offer: 'Offer to trade',
  },

  safety: {
    title: (name: string): string => `What to do about ${name}`,
    subtitle: 'Blocking is private. Reporting goes to a moderator.',
    block: 'Stop hearing this person',
    unblock: 'Hear this person again',
    blockHelp: 'You will not see anything they say. They are not told.',
    unblockHelp: 'You will hear them again from now on.',
    report: 'Report them to a moderator',
    reportHelp: 'A person reads every report. Reporting does not silence anybody by itself.',
    reasonLabel: 'What happened?',
    sendReport: 'Send the report',
    reportSent: 'Thank you. A moderator will read this.',
    blocked: (name: string): string => `You will no longer hear ${name}.`,
    unblocked: (name: string): string => `You will hear ${name} again.`,
    close: 'Close',
  },
} as const;

/** Turn any reason the connection gives us into a sentence for the player. */
export function errorMessage(reason: string): string {
  return strings.errors[reason] ?? strings.errors['unknown'] ?? reason;
}
